@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ScheduleCommandParser" as ScheduleCommandParser LOGIC_COLOR
participant "s:ScheduleCommand" as ScheduleCommand LOGIC_COLOR
participant "ScheduleCommand" as ScheduleCommandStatic <<class>> LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant ":Meeting" as Meeting MODEL_COLOR
end box

[-> LogicManager : execute(schedule)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(schedule)
activate AddressBookParser

create ScheduleCommandParser
AddressBookParser -> ScheduleCommandParser
activate ScheduleCommandParser

ScheduleCommandParser -> AddressBookParser
deactivate ScheduleCommandParser

AddressBookParser -> ScheduleCommandParser : parse(arguments)
activate ScheduleCommandParser

create Meeting
ScheduleCommandParser -> Meeting
activate Meeting

Meeting --> ScheduleCommandParser
deactivate Meeting

create ScheduleCommand
ScheduleCommandParser -> ScheduleCommand
activate ScheduleCommand

ScheduleCommand --> ScheduleCommandParser
deactivate ScheduleCommand

ScheduleCommandParser --> AddressBookParser : s
deactivate ScheduleCommandParser
ScheduleCommandParser -[hidden]-> AddressBookParser : s

AddressBookParser --> LogicManager : s
deactivate AddressBookParser
destroy ScheduleCommandParser

LogicManager -> ScheduleCommand : execute(m)
activate ScheduleCommand

ScheduleCommand -> Model : getFilteredPersonLisAt()
activate Model

Model --> ScheduleCommand
deactivate Model

ScheduleCommand -> ScheduleCommandStatic : createEditedPerson(personToEdit, meeting)
activate ScheduleCommandStatic

ScheduleCommandStatic --> ScheduleCommand : editedPerson
deactivate ScheduleCommandStatic

ScheduleCommand -> Model : setPerson(personToEdit, editedPerson)
activate Model

Model --> ScheduleCommand
deactivate Model

ScheduleCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model

Model --> ScheduleCommand
deactivate Model

create CommandResult
ScheduleCommand -> CommandResult
activate CommandResult

CommandResult --> ScheduleCommand
deactivate CommandResult

ScheduleCommand --> LogicManager : r
deactivate ScheduleCommand

[<--LogicManager : r
deactivate LogicManager
destroy ScheduleCommand
@enduml
